name: Release Drafter

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  UpdateReleaseDraft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
